version: "3.8"

services:
  app:
    container_name: suspicious-reading-detector
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    working_dir: /app
    stdin_open: true
    tty: true
